### ISSUE TITLE
pytest fail in test_api.py

### ISSUE THREAD

**Issue by gj94gj94ao4** [darkfeline/mir.dlsite#1]
Sorry for my poor English.
due to DLsite changes, it is possible that soup4 couldn't match some parses.
So pytest program find a Failure in your test_api.py line 42 with "RJ189758"

不知道是不是因為DLsite最近改版了，所以在執行pytest的時候api.fetch_work不能找到RJ189758的內容。
![image](https://user-images.githubusercontent.com/29171396/38007976-cfe721aa-327e-11e8-9fc1-57bb40660bcb.png)

**Comment by darkfeline** [comment]
The tests use fake pages, so DLSite changes will not affect it.  The tests work for me and the [CI](https://circleci.com/gh/darkfeline/mir.dlsite).  The problem is probably because of Windows, but I don't use Windows.  You have to post the entire error or I cannot tell what's wrong.  I use the library and it is not affected by DLSite changes.

pytest用假的网页，跟DLSite没关系。问题大概是Windows，但我不用Windows。你得把出错信息全部贴上。我平常用这软件没问题。

**Comment by gj94gj94ao4** [comment]
[pytest.log](https://github.com/darkfeline/mir.dlsite/files/1855240/pytest.log)
Did I need to give you something else?  Like environment.
我還需要給你什麼嗎?

**Comment by darkfeline** [comment]
Should be fixed

应该可以了。

**Comment by gj94gj94ao4** [comment]
great! Thanks a lot!
太好了  謝謝你
